### ISSUE TITLE
tag and release for v0.2.5

### ISSUE THREAD

**Issue by jasonkey** [tbepler/topaz#81]
Hi Topaz developers, 

Are you planning to tag and release v0.2.5 as was done for earlier releases? 
The README reads like 0.2.5 is an official release, but I wasn't sure if it is ready yet since I don't see it with prior releases.

`$ ./topaz --version`
prints
`TOPAZ 0.2.5a`

so maybe 0.2.5 is still in development? 
Thanks for the clarification, apologies if I am missing something here. 

Cheers, 
Jason

**Comment by tbepler** [comment]
Yes, we will be tagging and releasing 0.2.5 through conda, pypi, etc. Currently, the release isn't finalized which is why this hasn't been done yet. Largely because I haven't had time to fully check and set up the release, but also because there are a few bugs that have come to my attention that I would like to include fixes for in 0.2.5.

**Comment by jasonkey** [comment]
Understood - 
thanks for the update.
